### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by cedriking** [shlifedev/AmongUsMemory#14]
Please update offset or complete the guide: https://github.com/shlifedev/AmongUsMemory/blob/master/OffsetGuide.md

Thank you 👍

**Comment by shlifedev** [comment]
hello, current engineoffset.cs is latest!
and i added offset update guide 👍 
here
https://github.com/shlifedev/AmongUsMemory/blob/master/OffsetGuide.md

**Comment by PixelGM** [comment]
Can you make a vid for the explanation?

**Comment by shlifedev** [comment]
doesn't need video.. It's so easy. ;) If you know how to use the cheat engine, just follow the guide document.

**Comment by shlifedev** [comment]
if you still have problem, send me email. i will send you guide video.
