### ISSUE TITLE
How can i know that the player is impostor or not

### ISSUE THREAD

**Issue by PixelGM** [shlifedev/AmongUsMemory#15]
So i have researched, the green color is for local player, and the red is dead. But how about impostor?

**Comment by shlifedev** [comment]
use **PlayerInfo** in PlayerData class.

https://github.com/shlifedev/AmongUsMemory/blob/master/AmongUsMemory/Structs/PlayerInfo.cs
IsImposter variable :)

**Comment by PixelGM** [comment]
Thanks bro, now i can add the color of impostor
