### ISSUE TITLE
지도는 뭐로 그리신건가요?

### ISSUE THREAD

**Issue by H0ng** [shlifedev/AmongUsMemory#17]
지도는 뭐로 그리신건가요?

**Comment by shlifedev** [comment]
만들어놓고 기억은 안나는데 대충 아래처럼 작업했던거 같네요~~

1. 캐릭터를 대충 0,0 위치에 가깝게 위치시키시고 미니맵 스크린샷 캡쳐 해놓으세요.  
2. 그 뒤 맵에서 갈 수 있는 가장 왼쪽 벽에붙어서 거기 좌표를 따시고 미니맵 스크린샷 캡쳐 + 월드좌표(캐릭터위치) 기록 하세요!
3. 1,2번을 비교해서 월드 좌표의 distance, 스크린 좌표의 distance를 구하세요  ( a.x - b.x )
4. 그럼 월드 캐릭터 좌표가 10만큼 변하면 스크린좌표가 100만큼 변한다.. 이런 사실을 알 수 있습니다.

이후 이걸 이용해서 자기만의 수식을 이용해서 미니맵 오버레이를 만드시면 됩니다. 
그냥 게임 내 미니맵 포토샵에 붙여넣고 이쁘게 외곽선 따라 선 대충 그어서 사용하시면 됩니다.

**Comment by H0ng** [comment]
![K-001](https://user-images.githubusercontent.com/18163821/93629867-f33ecd00-fa23-11ea-9391-bdba462cdee0.png)
대충 시도해봣는데 게임상의 위치와 그려진 맵에 위치(검은색 점)가 다른데 어떻게 해야될까요?

**Comment by H0ng** [comment]
플레이 하고 있는 맵이 어떤 맵인지 알 수 있나요?

**Comment by H0ng** [comment]
> 만들어놓고 기억은 안나는데 (레이더 소스를 날려먹어서..) 대충 아래처럼 작업했던거 같네요~~
> 
> 1. 캐릭터를 대충 0,0 위치에 가깝게 위치시키시고 미니맵 스크린샷 캡쳐 해놓으세요.
>    캐릭터 좌표는 PlayerData.cs의 Position 변수로 콘솔에서 디버깅 하실 수 있습니다.
> 2. 그 뒤 맵에서 갈 수 있는 가장 왼쪽 벽에붙어서 거기 좌표를 따시고 미니맵 스크린샷 캡쳐 + 월드좌표(캐릭터위치) 기록 하세요!
> 3. 1,2번을 비교해서 월드 좌표의 distance, 스크린 좌표의 distance를 구하세요  ( a.x - b.x )
> 4. 그럼 월드 캐릭터 좌표가 10만큼 변하면 스크린좌표가 100만큼 변한다.. 이런 사실을 알 수 있습니다.
> 
> 여기까지 한거면 사실 다 한거죠. 내 캐릭터 위치대비 스크린좌표를 알 수 있으니까요
> 
> 이후 이걸 이용해서 자기만의 수식을 이용해서 미니맵 오버레이를 만드시면 됩니다.
> 그냥 게임 내 미니맵 포토샵에 붙여넣고 이쁘게 외곽선 따라 선 대충 그어서 사용하시면 됩니다.
> 어차피 게임 미니맵이 단순해서 선 찍찍 대충 그어서 쓰시면돼요.

혹시 맵에서 문이 어디가 닫혀있는지 열려있는지 알 수 있나요?
