### ISSUE TITLE
Can't use Write functions

### ISSUE THREAD

**Issue by thkdlflghlsdghilr** [shlifedev/AmongUsMemory#18]
I might be using it wrong but I can't use the write functions. How do they work?

**Comment by shlifedev** [comment]
Which write function did you use? (kill timer.. write imposter.. etc)

**Comment by thkdlflghlsdghilr** [comment]
I tried to use all of them. None of them worked but I am not totally sure how to use them in the first place.

**Comment by thkdlflghlsdghilr** [comment]
Here is the code I am using, not sure if it is correct, Can you please explain how the functions work on how to use them?
`                playerDatas = HamsterCheese.AmongUsMemory.Cheese.GetAllPlayers();
                foreach (var data in playerDatas)
                {
                    var name = HamsterCheese.AmongUsMemory.Utils.ReadString(data.PlayerInfo.Value.PlayerName);
                    listBox1.Items.Add(name + "       " + data.PlayerInfo.Value.IsImpostor);
                    data.WriteMemory_KillTimer(0);
                }`
