### ISSUE TITLE
Update Pointers

### ISSUE THREAD

**Issue by QuikkHakk** [shlifedev/AmongUsMemory#2]
Tried to run the example code.
But i got a null pointer exception in GetAllPlayers() because
byte[] playerAoB = Cheese.mem.ReadBytes(Pattern.PlayerControl_Pointer, Utils.SizeOf<PlayerControl>());
returns a null pointer.

So my question is, do I have to update the pointers or are they constant?

**Comment by shlifedev** [comment]
Hello, I will check this problem.

**Comment by QuikkHakk** [comment]
Thanks a lot

**Comment by shlifedev** [comment]
Hello! Can you tell me some information?

1. Game Version (Run Game, See Left Top Main Screen.), Currently **v2020.8.12s**
2. In Game Folder, GameAssembly.dll Binary Size. (My binary size is 15,277,056 bytes, 14.5mb)
 

And, Cheese Working Fine My laptop/desktop. 
Please Get the latest update and try again. 

(currently engineoffset.cs is latest.)

**Comment by shlifedev** [comment]
![](https://i.imgur.com/ojvGLwX.png)

Please Try YourCheese.exe In FreePlay Mode. (In freeplay mode, only local players are found.)

**Comment by QuikkHakk** [comment]
Thank you for taking the time.

I have checked the version now which is the same as for you.
The size of the GameAssembly.dll is 15,277,568 bytes for me.

Downloaded this project again and ran the YourCheese.exe

This is the error I get

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at HamsterCheese.AmongUsMemory.Utils.FromBytes[T](Byte[] bytes) in C:\Users\shlif\OneDrive\Desktop\Github\AmongUsMemory\AmongUsMemory\Utils.cs:line 15
   at HamsterCheese.AmongUsMemory.Cheese.GetAllPlayers() in C:\Users\shlif\OneDrive\Desktop\Github\AmongUsMemory\AmongUsMemory\Cheese.cs:line 132
   at YourCheese.Program.Main(String[] args) in C:\Users\shlif\OneDrive\Documents\GitHub\AmongUsMemory\YourCheese\Program.cs:line 16

**Comment by shlifedev** [comment]
Your and my GameAssembly.dll file different sizes. 
You downloaded the game from Steam?
Can you send me your GameAssembly.dll?

**Comment by shlifedev** [comment]
https://drive.google.com/file/d/1hoVsccmqTUvy5jnvt_W06u3SNDUoiUTk/view?usp=sharing

or use this GameAssembly dll.

**Comment by QuikkHakk** [comment]
Ive sent an request for your file. If its not working, I'll reinstall the game and if it's still not working then, I'll send you my file.

**Comment by shlifedev** [comment]
Oh, are you using the crack version? The crack version has a different binary size.
Please Update Your **EngineOffset.cs** here. it's crack version pointer.

```cs
namespace HamsterCheese.AmongUsMemory
{
    public sealed class Pattern
    {
        /// <summary>
        /// Get PlayerControl
        /// </summary>
        public static string PlayerControl_Pointer = "GameAssembly.dll+E22AE8";  //GameAssembly.dll+E22AE8
        public static string ShipStatus_Pointer = "GameAssembly.dll+E22AB4";
        /// <summary>
        /// Get PlayerControl.Get_Data();
        /// </summary>
        public static string PlayerControl_GetData = "55 8B EC 80 3D 58 06 ??";
    }
}


```

**Comment by QuikkHakk** [comment]
Ok that worked. Sorry for your time.

A friend of mine sent me the game, who has bought the game. So I thought it would has to be the real version.

But thanks a lot.

**Comment by shlifedev** [comment]
Oh. No problem. :) New offset Working fine for you?

**Comment by QuikkHakk** [comment]
Yup, working perfectly fine :)
