### ISSUE TITLE
Cheese.GetAllUsers() always returns an empty List

### ISSUE THREAD

**Issue by Assgent** [shlifedev/AmongUsMemory#22]
This seems to be a new bug, but Cheese.GetAllUsers() always returns an empty list regardless of conditions. Perhaps the game's offsets changed?

**Comment by shlifedev** [comment]
Hello, Sorry I am very busy at the company, so I cannot check the current issue. If game version has been updated, please check this document. Very easy. 

here : https://github.com/shlifedev/AmongUsMemory/blob/master/OffsetGuide.md

**Comment by ohkriss** [comment]
Here is updated offsets, just replace these with the ones in EngineOffset.cs.

`public static string PlayerControl_Pointer = "GameAssembly.dll+1468910";`
`public static string ShipStatus_Pointer = "GameAssembly.dll+146885C";`
`public static string AmongusClient_Pointer = "GameAssembly.dll+1468840";`
`public static string PlayerControl_GetData = "55 8B EC 80 3D 2A FC ??";`

**Comment by shlifedev** [comment]
@ohkriss  thank. 👍
