### ISSUE TITLE
[Feature request] More write mem functions, fix write mem, add documentation, update offset

### ISSUE THREAD

**Issue by thkdlflghlsdghilr** [shlifedev/AmongUsMemory#23]
Can you add functions to write:

- Color ID
- Pet ID
- Hat ID
- Name

Also as of writing this, all write memory functions do not work, possibly due to me not knowing how to use them properly which leads me into my next request

Write documentation, If you need help with writing it I would be glad to help but I need a working example of every function and so far a few don't work.

Finally, you did add a guide on how to update the offset but it is not totally clear and it is easier if u do it lol.

**Comment by ohkriss** [comment]
Everything works if you updated the offsets or git pulled this repo. 
I would suggest you to do some research yourself cause its not hard at all.

**Comment by thkdlflghlsdghilr** [comment]
I just pulled it and it did not work

**Comment by thkdlflghlsdghilr** [comment]
Sorry, I forgot to recompile. I am the big dum

**Comment by thkdlflghlsdghilr** [comment]
Writing to mem still does not work tho. Can you give an example of how to use it just in case I am doing something wrong?

**Comment by ohkriss** [comment]
`WriteMemory_LightRange(10.0f)`
`WriteMemory_Impostor(Convert.ToByte(true))`
