### ISSUE TITLE
Memory is not found on source nuget repository.

### ISSUE THREAD

**Issue by gir489** [shlifedev/AmongUsMemory#24]
The memory dependency is not a valid nuget dependency, it should be added as a compiled dependency or gitmodule from the source repo.

**Comment by Paffo** [comment]
The memory Nuget was recently removed, you can remove it from dependancies and add the dll as resource manually.

**Comment by Tiny-Lamma** [comment]
Just get rid of this file AmongUsMemory/packages.config (memory Nuget isn't used and this will throw the error, just include the memory.dll and this will run fine).

**Comment by shlifedev** [comment]
Deleted memory.dll from nuget. so i will add memory.dll my project self.

**Comment by SaSiNO97** [comment]
You can now install it again from NuGet, after removing it from packages.config

**Comment by mariomurrent-softwaresolutions** [comment]
Duplicate of [#19](https://github.com/shlifedev/AmongUsMemory/issues/19)
