### ISSUE TITLE
Module GameAssembly.dll was not found in module list!

### ISSUE THREAD

**Issue by Paffo** [shlifedev/AmongUsMemory#25]
Just downloaded the repo and compiled it, the Memory.dll logs:

[DEBUG] memory scan starting... (start:0x00010000 end:0x7ffffffeffff time:7:18:11 )
[DEBUG] memory scan completed. (time:7:18:12 )
Module GameAssembly.dll was not found in module list!
Modules: [Among Us.exe, 5963776],[ntdll.dll, 140710331547648],[wow64.dll, 140710310510592],[wow64win.dll, 140710321848320],[wow64cpu.dll, 2001403904]
[DEBUG] memory scan starting... (start:0x00010000 end:0x7ffffffeffff time:7:18:12 )
[DEBUG] memory scan completed. (time:7:18:13 )

As such the hack gives exception no data can be read since GameAssembly is not found.

Any idea why this might be?

**Comment by shlifedev** [comment]
Working fine for me.
Have you downloaded the latest release?

**Comment by Paffo** [comment]
Hello,
Thanks for your time and for this project.
At first i thought the problem were my modification, so i redownloaded the project and just compiled it,
still Memory.dll log tells me that the GameAssembly module is not found.
You are compiling for x64 or x86?

**Comment by Paffo** [comment]
Was compiling for wrong architecture, plus a system component was missing.
