### ISSUE TITLE
High CPU usage and not detecting map change

### ISSUE THREAD

**Issue by TSBYT** [shlifedev/AmongUsMemory#27]
Hello, I've started to write a client on your base, but it has a really high CPU Usage (40%). I'm running i7 9th gen, rtx2060, 16gb ram and ssd (my rig is good). I've tried to make the delay between memory reads bigger, but the client stops working. Could you optimize the memory reader?

**Comment by TSBYT** [comment]
I've been able to pin-point the error to one function: `Cheese.mem.ReadBytes(Pattern.ShipStatus_Pointer, Utils.SizeOf<ShipStatus>())` in the `GetShipStatus()` returns null, even tho the parameters are filled correctly;

**Comment by shlifedev** [comment]
thanks report :) i will check this problem soon.

**Comment by wolfy01** [comment]
Same issue with high cpu usage.

**Comment by KMcNickel** [comment]
Inn regards to the high CPU usage, I found a potential solution. The AoB scanning in memory.dll is pretty intensive so I modified the cheese.cs file in the AmongUsMemory project. Lines 85 and 144 both contain the AoBScan function and I just modified the arguments for both of them to Cheese.mem.AoBScan(0x04000000, 0x08000000, aobData, true, true);

The first 2 arguments just limits the scanned address range to a more reasonable area, reducing the CPU load. I'm not sure if these arguments are guaranteed to work for everyone every time, but I will doing some more testing and hopefully creating a PR soon.

**Comment by KMcNickel** [comment]
> Inn regards to the high CPU usage, I found a potential solution. The AoB scanning in memory.dll is pretty intensive so I modified the cheese.cs file in the AmongUsMemory project. Lines 85 and 144 both contain the AoBScan function and I just modified the arguments for both of them to Cheese.mem.AoBScan(0x04000000, 0x08000000, aobData, true, true);
> 
> The first 2 arguments just limits the scanned address range to a more reasonable area, reducing the CPU load. I'm not sure if these arguments are guaranteed to work for everyone every time, but I will doing some more testing and hopefully creating a PR soon.

This, by the way, dropped the CPU load on my desktop from 30% to 6-12%.
