### ISSUE TITLE
help  add feture complete all task

### ISSUE THREAD

**Issue by tonzsm** [shlifedev/AmongUsMemory#29]
who can add feture complete all task pls tell me

**Comment by TSBYT** [comment]
You can't really do that. And this is a source code for reading/writing Among Us memory. You have to write your own client.

**Comment by Paffo** [comment]
It is possible, but not with this, you have to hook an ingame function via c++  injected DLL or you have to convert this to a mono-inject project.

**Comment by shlifedev** [comment]
yeah. require internal hacking. You can easily hook functions with dll injection.

**Comment by tonzsm** [comment]
oh ok,thanks for all comment
