### ISSUE TITLE
How to be impostor?

### ISSUE THREAD

**Issue by RedLeader167** [shlifedev/AmongUsMemory#30]
(I'm not english)
I found "data.WriteMemory_Impostor(value);" string, but what value i need to use here? Please help!

(my code is:)
if (data.IsLocalPlayer == 1)
    data.WriteMemory_Impostor(1);

**Comment by RedLeader167** [comment]
P. S. 1 isn't working

**Comment by RedLeader167** [comment]
Sorry, i'm very dumb. I need to use Convert.ToByte(true)

**Comment by EthanZoneCoding** [comment]
did you fix it? I'm still having issues

**Comment by RedLeader167** [comment]
yes
When you need to make you impostor
if(data.IsLocalPlayer == 1)
{
data.WriteMemory_Impostor(Convert.ToByte(true));
}
You can also use false, if you need to turn off impostor mode

**Comment by RedLeader167** [comment]
Sorry if i made code typos, I'm on phone rn
