### ISSUE TITLE
Some questions 

### ISSUE THREAD

**Issue by RedLeader167** [shlifedev/AmongUsMemory#33]
1) Why antiviruses thinks Memory.dll file is infected? VirusTotal scan: https://www.virustotal.com/gui/file/ea6dc302b177dcd3974599e9512fe3a8994e60492cde0dbc058e9345638f4434/detection

2) How to change nicks, colors, skins, pets, etc?
3) How to make wallhack and noclip?

**Comment by RedLeader167** [comment]
pls help

**Comment by TSBYT** [comment]
bro this is open source, you make your own client, please don't start an issue for help

**Comment by RedLeader167** [comment]
> bro this is open source, you make your own client, please don't start an issue for help

ok

**Comment by pythonmcpi** [comment]
For number 1, I think it's due to the fact that memory.dll scans memory for values, which trojans/rootkits may try to do to modify program behavior/hijack a process.
