### ISSUE TITLE
data => 0

### ISSUE THREAD

**Issue by ggpabuk** [shlifedev/AmongUsMemory#34]
**I have rechecked the pointers offsets**
Code: https://pastebin.com/ufEgqtQP
![scr](https://user-images.githubusercontent.com/59561857/94689987-32302500-0338-11eb-94cd-0f39b47f7e22.png)

**Comment by RedLeader167** [comment]
Это происходит из-за того, что идет голосование, в обычной игре все ок. Если в обычной игре тоже самое, отпишись, может помогу

**Comment by ggpabuk** [comment]
> Это происходит из-за того, что идет голосование, в обычной игре все ок. Если в обычной игре тоже самое, отпишись, может помогу

Запустил в меню (от админа), зашёл на паб. Эта херня с начала игры

**Comment by ggpabuk** [comment]
Cheese.GetAllPlayers() returns 0 indexes
![image](https://user-images.githubusercontent.com/59561857/94727911-12185a00-0368-11eb-8d63-bbfbd5abe8c0.png)

**Comment by DiamondMiner88** [comment]
Are you using the latest version of Among Us? (v2020.9.22s)

**Comment by ggpabuk** [comment]
> Are you using the latest version of Among Us? (v2020.9.22s)

yes
