### ISSUE TITLE
Document which current Among Us version the offsets are based on.

### ISSUE THREAD

**Issue by DiamondMiner88** [shlifedev/AmongUsMemory#35]
Spent 2 hours trying to figure out why setting imposter for a player made the rest stop working, before realizing I had v2020.9.9 instead of the latest.
Saying which version the offsets are based on in `README.md` or something would be great for new people.

**Comment by dru1d-foofus** [comment]
That's a fair point. The offsets currently pulled for this project are for v2020.9.22. The @shlifedev did make sure to include an offset finding guide for in case of the offsets changing.
