### ISSUE TITLE
Cannot get it working

### ISSUE THREAD

**Issue by MrDucxy** [shlifedev/AmongUsMemory#36]
Updated the offsets, tried the example program and I get an exception. Tried my own program and it doesnt log anything to console at all.

**Comment by oOHiyoriOo** [comment]
1. u have to set "YourCheese" as start project than u can run it

**Comment by MrDucxy** [comment]
> 1. u have to set "YourCheese" as start project than u can run it

I got it to run and then I got an exception in Utils.cs on both my own cheat and the YourCheese one

**Comment by oOHiyoriOo** [comment]
tell me the error, maybe i can help you.
