### ISSUE TITLE
Error: Method expected in example code

### ISSUE THREAD

**Issue by randomcmd** [shlifedev/AmongUsMemory#38]
![Screenshot_30](https://user-images.githubusercontent.com/63674603/94932089-e2349800-04c8-11eb-9e92-7e850a66e917.png)

**Comment by RedLeader167** [comment]
just add () after func name
it's so easy

**Comment by RedLeader167** [comment]
HamsterCheese.AmongUsMemory.Cheese.ObserveShipStatus(OnDetectJoinNewGame())

**Comment by DiamondMiner88** [comment]
```cs
HamsterCheese.AmongUsMemory.Cheese.ObserveShipStatus((x) => OnDetectJoinNewGame());
```
syntax error, not related
