### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by markito12** [shlifedev/AmongUsMemory#4]
I get no information from the current match

![Screenshot_10](https://user-images.githubusercontent.com/31602075/91504982-e3105380-e8a4-11ea-8639-a90c2d60cd13.png)

**Comment by markito12** [comment]
playerDatas.Count is 0

also `if(playerDatas == null && playerDatas.Count == 0) return; ` i think this line should be
`if(playerDatas == null || playerDatas.Count == 0) return; `

**Comment by markito12** [comment]
I got it to work, but now its just spamming the table

**Comment by shlifedev** [comment]
Currently Not work In Lobby. You can get player only after the game starts.
and i will add the thread delay.

**Comment by shlifedev** [comment]
i edited like this.

![image](https://user-images.githubusercontent.com/49047211/91510992-9581fe00-e919-11ea-8be1-93e333de762b.png)

 
green : me  
yellow : imposter  
red : died player

**Comment by markito12** [comment]
Nice!!, great job,  i was doing that myself with `IsDead` and `IsImpostor`
