### ISSUE TITLE
Question: List of all changeable player variables?

### ISSUE THREAD

**Issue by randomcmd** [shlifedev/AmongUsMemory#40]
Can someone tell me a list of all player variables that can be changed? For example values like: IsImposter Position IsDead InVent

**Comment by oOHiyoriOo** [comment]
u can type data.Instance. and should get everything u should be able to write / read
same for Data.PlayerInfo.Value.

**Comment by randomcmd** [comment]
im too stupid lmao can you reply to me with code that would change the player color/pet for example?

**Comment by shlifedev** [comment]
use write memory function in playerdata.cs

example  implement


```cs
       public void WriteMemory_Impostor(byte value)
        {
            var targetPointer = Utils.GetMemberPointer(playerInfoOffset_ptr, typeof(PlayerInfo), "IsImpostor"); 
            Cheese.mem.WriteMemory(targetPointer.GetAddress(), "byte", value.ToString());
        }
```

**Comment by randomcmd** [comment]
Im sorry if im asking too many questions, but my code isn't really working and I don't know why
`public void WriteMemory_ColorID(int value)
        {
            var targetPointer = Utils.GetMemberPointer(playerInfoOffset_ptr, typeof(PlayerInfo), "ColorID");
            Cheese.mem.WriteMemory(targetPointer.GetAddress(), "int", value.ToString());
        }

`

**Comment by shlifedev** [comment]
use **offset_ptr** instead of **playerInfoOffset_ptr**

**Comment by randomcmd** [comment]
I've tried, but it still throws an Exception
```
public void WriteMemory_ColorID(byte value)
        {
            var targetPointer = Utils.GetMemberPointer(offset_ptr, typeof(PlayerInfo), "ColorID");
            Cheese.mem.WriteMemory(targetPointer.GetAddress(), "byte", value.ToString());
        }
```

**Comment by shlifedev** [comment]
@randomcmd 
       public void WriteMemory_ColorID(byte value)
        {
            var targetPointer = Utils.GetMemberPointer(playerInfoOffset_ptr, typeof(PlayerInfo), "ColorId"); 
            Cheese.mem.WriteMemory(targetPointer.GetAddress(), "byte", value.ToString());
        }


Change 'ColorID' => 'ColorId'
haha :)
