### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by goddamnitgreg** [shlifedev/AmongUsMemory#41]
Could you use this to allow yourself to be imposter??

**Comment by randomcmd** [comment]
yes but only client side there is a method for that in player data

**Comment by oOHiyoriOo** [comment]
i mean u can set yourself imposter, but only client sided // if youre not the host u have to "kill" as fast an much as you can to trigger a imposter win but even this doiesnt works perfectly.
But if you're the host theres no problem at all

**Comment by goddamnitgreg** [comment]
So assuming I'm the host (I usually am), I would be able to set myself as imposter. So where and what code do I need to edit in order to do this.

**Comment by oOHiyoriOo** [comment]
u need the call the write_imposter on yourself. u can take a look into my 'ZeroUs' repo on my account there's a working set imposter.

**Comment by pythonmcpi** [comment]
> u need the call the write_imposter on yourself. u can take a look into my 'ZeroUs' repo on my account there's a working set imposter.

Just wondering, why didn't you fork this repo? This way it would be possible to (easily) compare the two, in case this repo gets updated.

**Comment by oOHiyoriOo** [comment]
> > u need the call the write_imposter on yourself. u can take a look into my 'ZeroUs' repo on my account there's a working set imposter.
> 
> Just wondering, why didn't you fork this repo? This way it would be possible to (easily) compare the two, in case this repo gets updated.

That's a great question, gonna answer it as soon i have a reason to not just Fork. Xd.
