### ISSUE TITLE
How do I read IntPtr?

### ISSUE THREAD

**Issue by TheBackdoor** [shlifedev/AmongUsMemory#44]
Im new in gamehacking. I know the basics but idk how to read IntPtr.

Like: How do I get the value of PlayerData.PlayerInfo.Value.Tasks ? do I need to do .ToPointer() and read it with the Memory class?
and how to read Ship.AllCameras? what do I get if I get the value?

**Comment by EastArctica** [comment]
For an example of `PlayerData.PlayerInfo.Value.Tasks` Heres how to get the total task count
```
IntPtr tasks = data.PlayerInfo.Value.Tasks + 0xC;
int taskCount = HamsterCheese.AmongUsMemory.Cheese.mem.ReadInt(tasks.GetAddress());
```
aka, take the Tasks, add 0xC to it(found this with cheatengine by putting in tasks.GetAddress() then exploring the memory for changes) then just read the memory at that location. Another example is for total times the task count has been modified which is at 0x10. I am not a very good reverser either but I just found these by luck mostly, if you've got any questions on how i got these then ask away. If you want to know how to get the tasks as text, they are most likely stored as a int somewhere then you need to parse that to a string somehow.
