### ISSUE TITLE
emergency meeting/dead body found event?

### ISSUE THREAD

**Issue by matthewpetch** [shlifedev/AmongUsMemory#46]
I want to write a discord bot that mutes/unmutes everyone on a meeting/dead body found. Can keep dead people muted with the existing stuff, just wondering if an event can be raised for whenever a vote is happening?

**Comment by SaSiNO97** [comment]
I want to do exactly the same, has anyone found a solution?

**Comment by RedLeader167** [comment]
idk, you can try every x seconds check every player, and if dead - mute, alive - unmute (but you still need to somehow find bytes of emergency meeting)

**Comment by matthewpetch** [comment]
well it looks like there is a meeting_status field now 

https://github.com/shlifedev/AmongUsMemory/commit/06a1463a8a31dbc1f42e4d3c854d198db25616c5
