### ISSUE TITLE
Why should I copy '7' bytes from player.getdata() address? 

### ISSUE THREAD

**Issue by ShinhuPark** [shlifedev/AmongUsMemory#48]
From the offset guide link in README.md, I followed through all steps and working just fine, but i don't understand why I should copy 7 bytes from hex view of player.getdata()? why not 4 or 6 or anything else? How can I know how many bytes to copy?

**Comment by lanylow** [comment]
So look, current working pattern is `55 8B EC 80 3D FA 1B`, if you scan it, there is only one occurrence of it, so you are surely getting the right address, but if you scan the same signature with one byte less (`55 8B EC 80 3D FA`) there are like 87 occurrences of the same pattern so most likely you will not get the right address.
