### ISSUE TITLE
How did you make the 2D Radar?

### ISSUE THREAD

**Issue by nemt7** [shlifedev/AmongUsMemory#49]
More like a question but...

**Comment by DiamondMiner88** [comment]
> **Don't ask me how to draw a radar :)**

From README.md

**Comment by nemt7** [comment]
![image](https://user-images.githubusercontent.com/61268470/97051455-861cdb00-157f-11eb-99aa-e41b99766754.png)
can't seem to get it to work.

sry if i'm stupid. Pretty new in this world of code

**Comment by TheRealHona** [comment]
![image](https://user-images.githubusercontent.com/10430890/97070469-c0d45100-161b-11eb-8625-a94f56c9b798.png)

I made my own tool, basically I got an image of the map, found a way to convert the in game coordinates to coordinates on the image, then just draw on the image.

If you want to overlay the radar (mine is on a separate window, you might need to hook into a draw event, or maybe look into another way - maybe DirectX)

**Comment by shlifedev** [comment]
@TheRealHona  lol!!

**Comment by TheRealHona** [comment]
Hehehe :) , I moved some of the nice tools to the GUI too (become imposter, no cooldown, etc)
