### ISSUE TITLE
(10.22s) NEW OFFSETS HERE!

### ISSUE THREAD

**Issue by ggpabuk** [shlifedev/AmongUsMemory#52]
<h1>NEW OFFSETS</h1>
<img src="https://i.imgur.com/dRR0pCU.png" alt="drawing" width="200"/>

**Comment by KMcNickel** [comment]
The new update (10.22) added some code Obfuscation making it more difficult to find these variables. They are there but they have randomly generated names.

I have found what I believe to be the playercontrol, but I am still working on the others.

**Comment by ggpabuk** [comment]
> The new update (10.22) added some code Obfuscation making it more difficult to find these variables. They are there but they have randomly generated names.
> 
> I have found what I believe to be the playercontrol, but I am still working on the others.

Thanks, please share the offstets after finding them

**Comment by KMcNickel** [comment]
I tried this once, in freeplay, in Mira and it worked, but I have not done enough testing to say if this is correct.

PlayerControl: 144BB70
Ship Status: 144BB58
Player Control Get Data: 55 8B EC 80 3D FA 1B ??

**Comment by schalk-b** [comment]
> I tried this once, in freeplay, in Mira and it worked, but I have not done enough testing to say if this is correct.
> 
> PlayerControl: 144BB70
> Ship Status: 144BB58
> Player Control Get Data: 55 8B EC 80 3D FA 1B ??

Yup, those are the same offsets I found after figuring out the obfuscation. Also to note is there is a new field in ShipStatus (I'm not sure what it does. But I had to add:

`[System.Runtime.InteropServices.FieldOffset(0xD8)]    public uint SomethingUnknown;`

**Comment by ggpabuk** [comment]
I think `PlayerData.IsLocalPlayer` was broken

**Comment by AlexisAG** [comment]
How can you figured out the obfuscation ?
Have you any reference link to learn it ? It's an interesting subject, i'd like to study it.
