### ISSUE TITLE
How to do noclip?

### ISSUE THREAD

**Issue by ggpabuk** [shlifedev/AmongUsMemory#55]

**Comment by pythonmcpi** [comment]
It isn't very easy even with this tool.
You would need to:
1. Locate the collision check(s)
2. Overwrite them with NOPs
3. Hope it doesn't crash

**Comment by KMcNickel** [comment]
> It isn't very easy even with this tool.
> 
> You would need to:
> 
> 1. Locate the collision check(s)
> 
> 2. Overwrite them with NOPs
> 
> 3. Hope it doesn't crash

4. Hope the server anti-hack features don't kick you
