### ISSUE TITLE
Doesnt Work With Recent Version?

### ISSUE THREAD

**Issue by Yeetukus** [shlifedev/AmongUsMemory#57]
How do I set it up? in the Guide, it says to find PlayerControl but it doesn't exist.

**Comment by KMcNickel** [comment]
New offsets are in #52

**Comment by 112batman** [comment]
Latest update broke it again

**Comment by dbarbosapn** [comment]
@112batman Check #60 and follow the offset guide!

**Comment by KMcNickel** [comment]
> @112batman Check #60 and follow the offset guide!

The latest version is 11.17, the classes you found for 11.4 have changed names so they would need to be found again.

**Comment by KMcNickel** [comment]
Class names for 11.17:

PlayerControl: JENJGDMOEOC
ShipStatus: JBBAENBKONG

**Comment by thkdlflghlsdghilr** [comment]
Where/How do apply those values in EngineOffset.cs?
```
public static string PlayerControl_Pointer = "GameAssembly.dll+144BB70";
public static string ShipStatus_Pointer = "GameAssembly.dll+144BB58";
public static string AmongusClient_Pointer = "GameAssembly.dll+1468840";
public static string PlayerControl_GetData = "55 8B EC 80 3D FA 1B ??";
```

**Comment by KMcNickel** [comment]
> Where/How do apply those values in EngineOffset.cs?
> 
> ```
> 
> public static string PlayerControl_Pointer = "GameAssembly.dll+144BB70";
> 
> public static string ShipStatus_Pointer = "GameAssembly.dll+144BB58";
> 
> public static string AmongusClient_Pointer = "GameAssembly.dll+1468840";
> 
> public static string PlayerControl_GetData = "55 8B EC 80 3D FA 1B ??";
> 
> ```

Look at the offset guide, the "PlayerControl" and "ShipStatus" classe names wont show up in mono because they have been obfuscated so you have to look for the names I put in that reply instead. Everything else in the guide is the same.

**Comment by schalk-b** [comment]
Fresh new offsets:
public static string PlayerControl_Pointer = "GameAssembly.dll+143BFC0"; // JENJGDMOEOC
public static string ShipStatus_Pointer = "GameAssembly.dll+143C110"; //EIEMHBCHLNI
public static string PlayerControl_GetData = "55 8B EC 80 3D 7A F8 ??"; // JENJGDMOEOC.get_Data

**Comment by Cryental** [comment]
//12.3s
        public static string PlayerControl_Pointer = "GameAssembly.dll+193C4B4";
        public static string ShipStatus_Pointer = "GameAssembly.dll+193BE9C";
        public static string PlayerControl_GetData = "55 8B EC 80 3D EC C8 ??";

**Comment by CrispCrew** [comment]
> ```
>     //12.3s
>     public static string PlayerControl_Pointer = "GameAssembly.dll+193C4B4";
>     public static string ShipStatus_Pointer = "GameAssembly.dll+193BE9C";
>     public static string PlayerControl_GetData = "55 8B EC 80 3D EC C8 ??";
> ```

Game literally just updated, lol

**Comment by Cryental** [comment]
I will look and update here.

**Comment by CrispCrew** [comment]
PlayerControl = 0x1BE11CC
ShipStatus = 0x1BE1054
var aobScan = Functions.mem.AoBScan("55 8B EC 80 3D 12 40 ??");

**Comment by CrispCrew** [comment]
ShipStatus = 0x1C56C38 //KHNHJFFECBP
AmongUsClient = 0x1C57F54 //FMLLKEACGIO
PlayerControl = 0x1C57F7C //FFGALNAPKCD
var aobScan = Functions.mem.AoBScan("55 8B EC 80 3D A9 D1 ??");

**Comment by Cryental** [comment]
You're doing a great job! Thank you~

**Comment by CrispCrew** [comment]
> You're doing a great job! Thank you~

Thx

**Comment by CrispCrew** [comment]
@shlifedev I no longer use your source in my source but if you want, I will keep creating pull requests when I remember and posting new offsets in a commit.

**Comment by AlexisAG** [comment]
public static string PlayerControl_Pointer = "GameAssembly.dll+1C57F7C"; 
        public static string ShipStatus_Pointer = "GameAssembly.dll+1C56C38";
        public static string AmongusClient_Pointer = "GameAssembly.dll+1C57F54";
        public static string PlayerControl_GetData = "55 8B EC 80 3D A9 D1 ??";

I have that offsets, but `Cheese.GetShipStatus();` return 0 value for all ShipStatus Properties..

It happens because `resultInst.MapScale > 0.1f` from  `Cheese.GetShipStatus();`  is always false.

Do you have any ideas ?

**Comment by CrispCrew** [comment]
Try using 1C57F54 for ShipStatus?

**Comment by CrispCrew** [comment]
> ```
>     public static string PlayerControl_Pointer = "GameAssembly.dll+1C57F7C"; 
>     public static string ShipStatus_Pointer = "GameAssembly.dll+1C56C38";
>     public static string AmongusClient_Pointer = "GameAssembly.dll+1C57F54";
>     public static string PlayerControl_GetData = "55 8B EC 80 3D A9 D1 ??";
> ```
> 
> I have that offsets, but `Cheese.GetShipStatus();` return 0 value for all ShipStatus Properties..
> 
> It happens because `resultInst.MapScale > 0.1f` from `Cheese.GetShipStatus();` is always false.
> 
> Do you have any ideas ?

Try using 1C57F54 for ShipStatus?

**Comment by AlexisAG** [comment]
> > ```
> >     public static string PlayerControl_Pointer = "GameAssembly.dll+1C57F7C"; 
> >     public static string ShipStatus_Pointer = "GameAssembly.dll+1C56C38";
> >     public static string AmongusClient_Pointer = "GameAssembly.dll+1C57F54";
> >     public static string PlayerControl_GetData = "55 8B EC 80 3D A9 D1 ??";
> > ```
> > 
> > 
> > I have that offsets, but `Cheese.GetShipStatus();` return 0 value for all ShipStatus Properties..
> > It happens because `resultInst.MapScale > 0.1f` from `Cheese.GetShipStatus();` is always false.
> > Do you have any ideas ?
> 
> Try using 1C57F54 for ShipStatus?

It doesn't work.

I have a quick fix (it's clearly not the best way).

In **Cheese.GetShipStatus()**

                    if (resultInst.MapScale < 6470545000000 && resultInst.MapScale >= 0f)
                    {  
                        shipStatus = resultInst;  
                    }

In **Cheese._ObserveShipStatus()**

                if (prevShipStatus.OwnerId != shipStatus.OwnerId || (prevShipStatus.OwnerId == shipStatus.OwnerId && shipStatus.Timer > 0f))
                {
                    prevShipStatus = shipStatus;
                    onChangeShipStatus?.Invoke(shipStatus.Type);
                }
