### ISSUE TITLE
The example code seems broken.

### ISSUE THREAD

**Issue by CodePanter** [shlifedev/AmongUsMemory#6]
The game was updated yesterday, could this have affected your API? I don't get any useful output, just a flashing screen with the following: 

| offset | netId | OwnerID | PlayerID | spawnid | spawnflag |

**Comment by shlifedev** [comment]
Hello I will update it.

**Comment by shlifedev** [comment]
updated!

**Comment by CodePanter** [comment]
Thank you, but it seems a few hours after your update, the game got another update.  The version is now v2020.9.1s.

**Comment by shlifedev** [comment]
ok, wait a minute

**Comment by shlifedev** [comment]
updated :)

**Comment by CodePanter** [comment]
This seems to work now, thank you! I've been playing with this code for a bit now, and am trying to detect whether I won or lost at the end of a game. Do you have any suggestions for how I could do this? I was hoping it might be in the AmongUsClient struct, but I can't seem to use that with the current API.

**Comment by shlifedev** [comment]
yeah. you can detect. it's pseudo code

int impostorCount = 0;
int playerCount = 0;
list<playerdata> players = null;
void onDetectNewGame()
{
     players = getAllPlayers()
     playerCount = 0;
     impostorCount = 0;
     foreach(var p in players)
     {
             if(p.playerInfo.isImpostor == 1) impostorCount ++;
             else playerCount++;
     }
}

//0 == none
//1 == citizen Win
//2 == impostorWin
int GetWinTeam()
{
     int playerDeadCount = 0;
     int impostorDeadCount = 0;
  
    foreach(var p in players..)
    {
            if(p.playerInfo.isDead ==1 && p.playerInfo.isImpostor) impostorDeadCount ++;
            if(p.playerInfo.isDead ==1 && !p.playerInfo.isImpostor) playerDeadCount++;
    }
   
 
   if(impostorCount == impostorDeadCount) return 1;
   else if( (playerCount-playerDeadCount) <= impostorCount ) return 2;
   return 0;
}
