### ISSUE TITLE
New Offset not working

### ISSUE THREAD

**Issue by dbarbosapn** [shlifedev/AmongUsMemory#60]
Hello!

I've been trying to use AmongUsMemory but I found out that the offsets for 2020.9.22s are working but the newer ones are not!

I think you should update the Offset guide to help get it from the new obfuscation.

Thanks! 👍

**Comment by KMcNickel** [comment]
I don't fully understand your problem, so I'm going to ask a few questions to get some clarification.
- Are you running version 10.22 of the game?
- Are you saying that changing EngineOffsets.cs to the values from #52 and recompiling the code causes the program to be unable to work?
(I just looked and although the comment in EngineOffset.cs says 9.22, it is actually the 10.22 offsets, but it doesn't look like the code has been recompiled)

To address your last point, the issue with getting the values from the obfuscation is that there likely won't be enough consistency between versions to obtain any repeatability. If I have time, I'll submit a PR to change the offset update guide to mention this, but it will be hard to update it in any meaningful way that allows people to find the new offsets.

**Comment by dbarbosapn** [comment]
Hey, thanks for replying.

I'm saying that the values from #52 are not working for 10.22 on my side. But the ones on the previous commit of EngineOffsets.cs do work for 9.22. Maybe it's some deviation on the offsets due to external factors (?). That's why I'd love to know how to get those.

But if you plan to update the guide, that'd be awesome already!

**Comment by KMcNickel** [comment]
I have a fork of this and I put the class names in the comments. Below is a picture that has the names for the player on line 7 and the ship on line 8, try those names with the offset guide and that should help get some answers at least for this version. To my knowledge, there shouldn't be any differences between my copy of 10.22 and yours, but might as well as check.

![image](https://user-images.githubusercontent.com/37396126/99604896-6a102c00-29bb-11eb-8499-83f523103cf5.png)

**Comment by dbarbosapn** [comment]
Thank you a lot for that!

The offsets for the classes are the same. But the get_Data is not! 😮 

![Printscreen](https://user-images.githubusercontent.com/25279098/99685764-da31b700-2a7a-11eb-8b51-d11bdc7c05bb.JPG)

And I changed, but still doesn't work :smile: But it's some progress.

Thank you!!

**Comment by dbarbosapn** [comment]
Nevermind! I got it working.

**And I also got it working for the latest 11.4 version. The classes are:**

**PlayerControl: ** APNNOJFGDGP
**ShipStatus: ** OLEKJGCEKAM

I'm closing the issue.
