### ISSUE TITLE
Mono Dissector not working on v2020.12.9s

### ISSUE THREAD

**Issue by WilliamJChen** [shlifedev/AmongUsMemory#63]
In Mono dissector, under Assembly-CSharp.dll, there is no "PlayerControl". Most of the values also are not text.
![image](https://user-images.githubusercontent.com/16550634/102806038-26c62600-438a-11eb-9df2-8037f6755580.png)
![image](https://user-images.githubusercontent.com/16550634/102805786-bd461780-4389-11eb-88a5-03f8d7a0ab8e.png)

**Comment by WilliamJChen** [comment]
Ran mono dissector on v2020.8.31s, and it worked
![image](https://user-images.githubusercontent.com/16550634/102805907-f1b9d380-4389-11eb-99e7-c7090040a750.png)
![image](https://user-images.githubusercontent.com/16550634/102805919-f7171e00-4389-11eb-8512-bce9c83e8194.png)

**Comment by KMcNickel** [comment]
Class names in recent versions were obfuscated to reduce hacking. See #60 and #57 for a little more info.

**Comment by WilliamJChen** [comment]
ahh, that's what I was thinking. What's the new strategy for finding the class name?

**Comment by KMcNickel** [comment]
Some attributes are still in plain text, going through the structs as defined in the code here and using the find tool in mono can help figure it out
