### ISSUE TITLE
The AmongUsClient struct is unused.

### ISSUE THREAD

**Issue by Extremelyd1** [shlifedev/AmongUsMemory#7]
The struct for the AmongUsClient is never read in from memory. Is there any way you could add this?
Or if you could explain how you found the PlayerControl pointer offset, then I could maybe help finding this offset.

**Comment by ImRetroo** [comment]
+1

**Comment by Alextilt** [comment]
+1

**Comment by ImAleeexx** [comment]
+1

**Comment by shlifedev** [comment]
Hello, sorry for the late response. I'm busy these days ;)
i will add it soon!

**Comment by fedebabrauskas** [comment]
@shlifedev could you add an example of how to read the AmongUsClient struct? Thank you!
